### ISSUE TITLE
guest orders doesn't work

### ISSUE THREAD

**Issue by theomanus** [FriendsOfShopware/FroshPlatformHtmlMinify#10]
### PHP Version

7.4

### Shopware Version

v6.4.6.1

### Actual behaviour

On register if user wants to register as guest, it doesn't work.

### Expected behaviour

Should work with guest orders.

### Steps to Reproduce?

Bei Anhaken der Checkbox, dass man als Gast bestellen möchte (kein Kundenkonto anlegen), verschwinden die Passwortfelder (Pflichtfelder) nicht. Ergo kann man diesen Bildschirm nicht verlassen und daher keine Bestellung aufgeben, ohne ein Kundenkonto anzulegen.
Das erwartete Verhalten ist, dass bei Anhaken der Checkbox die Passwortfelder verschwinden.

**Comment by tinect** [comment]
Hey @theomanus 

you're not using the default theme, are you? This error sounds generic.
To be able to assist you, please check the console for errors and send me a public url where this occurs.

**Comment by theomanus** [comment]
Hi @tinect,

no, we have our own theme. But we installed that plugin in two different shops. And both had the same issue.
I will try to rebuild it on staging.

**Comment by theomanus** [comment]
ok, we found the issue in our theme. 
sorry for the inconvenience.

**Comment by tinect** [comment]
> ok, we found the issue in our theme. sorry for the inconvenience.

No problem :-)
