### ISSUE TITLE
Breaks Adyen-CC-Payments with official Plugin

### ISSUE THREAD

**Issue by b3nl** [FriendsOfShopware/FroshPlatformHtmlMinify#11]
### PHP Version

All

### Shopware Version

>= 6

### Actual behaviour

Enabling this plugin "breaks" the codes of:

https://github.com/Adyen/adyen-shopware6/blob/8bf1f65c05f83b51fed0bfa1d7ef9a49ca49d2b8/src/Resources/views/storefront/component/payment/adyencheckout.html.twig on document.querySelector('#adyen-checkout-configuration').dataset.

JS-Exception says that document.querySelector('#adyen-checkout-configuration') is null.

### Expected behaviour

Checkouts Work.

### Steps to Reproduce?

Check Every-Shop with Adyen and this plugin with cc payments

**Comment by tinect** [comment]
Sadly, I don't have any access for Adyen. While it looks plugin specific, it's hard to get into detail.
If you find anything, feel free to create PR.

**Comment by shyim** [comment]
Can you maybe provide an example rendered HTML?
