### ISSUE TITLE
UnterminatedStringException on Language Switch PDP

### ISSUE THREAD

**Issue by Isengo1989** [FriendsOfShopware/FroshPlatformHtmlMinify#12]
### PHP Version

7.4

### Shopware Version

6.4.11.1

### Actual behaviour

When calling the detailpage with a french translation an error occurs

`[2022-06-03T12:04:22.483637+00:00] request.CRITICAL: Uncaught PHP Exception JSMin\UnterminatedStringException: "JSMin: Unterminated String at byte 5244: '," at /home/www-data/shops/XXXXX/vendor/mrclay/jsmin-php/src/JSMin/JSMin.php line 214 {"exception":"[object] (JSMin\\UnterminatedStringException(code: 0): JSMin: Unterminated String at byte 5244: ', at /home/www-data/shops/XXXXXX/vendor/mrclay/jsmin-php/src/JSMin/JSMin.php:214)"} []
`### 

### Expected behaviour

Work on language shops

### Steps to Reproduce?

Switch the PDP from german to french for example

Problem seems to occur in when using the minifyJavascript() and is probably related to french apostrophs etc.

**Comment by tinect** [comment]
Could you please give something to reproduce the error? :-)

**Comment by tinect** [comment]
Do you use composer installation? If so, which version of mrclay/jsmin-php is installed on your side?

**Comment by Isengo1989** [comment]
Yes we use the composer install

From my composer.lock

```
"name": "mrclay/jsmin-php",
            "version": "2.4.1",
```

I will pass the info to the plugin dev since it is external.

**Comment by tinect** [comment]
Okay, I've hackes small tests, also seeing your example not crashing.
