### ISSUE TITLE
JS Fehler in Verbindung mit "Wunsch-Lieferdatum / Abhol-Termin (Datum & Uhrzeit) (SW6)"

### ISSUE THREAD

**Issue by xp24** [FriendsOfShopware/FroshPlatformHtmlMinify#13]
### Question

Moin, es gibt einen Fehler wenn man euer Plugin zusammen mit "Wunsch-Lieferdatum / Abhol-Termin (Datum & Uhrzeit) (SW6)". Laut Entwickler des anderen Plugins seid ihr Schuld, Kommunikation anbei:

Problembeschreibung / Eindeutige Anleitung zur Reproduktion:
xp24 - Hallo, scheinbar sorgt ein JS Fehler im Checkout für Verkaufsabbrüche, so das wir das Plugin deaktivieren mussten.

Bei aktiviertem Plugin kommt folgender JS Fehler in der Konsole.
Uncaught TypeError: can't access property "frontend.cookie.offcanvas", window.router is undefined

HVBj https://www.home-coral.de/theme/21a1ea32873095f741d3b9d2edbeabaa/js/all.js?16698863311212030:5
i https://www.home-coral.de/theme/21a1ea32873095f741d3b9d2edbeabaa/js/all.js?16698863311212030:4
n https://www.home-coral.de/theme/21a1ea32873095f741d3b9d2edbeabaa/js/all.js?16698863311212030:4
r https://www.home-coral.de/theme/21a1ea32873095f741d3b9d2edbeabaa/js/all.js?16698863311212030:4
<anonymous> https://www.home-coral.de/theme/21a1ea32873095f741d3b9d2edbeabaa/js/all.js?16698863311212030:5
Ohne Ihr integriertes Plugin gibt es diesen Fehler nicht.

codiverse/Constantin Höft  - Guten Abend,
das Plugin HTML Minify ist Schuld: https://forum.shopware.com/t/alle-links-im-frontend-weg-paginator-sorting-filter-und-artikelvarianten-ohne-funktion/94608
Ich habe es deaktiviert und sehe nun den Datepicker korrekt.
Viele Grüße,
Constantin Höft

xp24 - Hallo Herr Höft, ehrlich gesagt bin ich noch nicht überzeugt. Die Posts sind vom Mai und Juni, unser Problem ist "neu" und alle anderen Sachen funktionieren wenn das angesagte Plugin aktiv und Ihres inaktiv sind. Andersrum geht kein JS mehr wenn der Datepicker auf der Seite ist, also im Checkout. Ich würde mich freuen wenn das gelöst werden würde, das mutmaßliche deaktivieren eines anderen Plugins kann es nicht sein. Vielleicht kommunizieren Sie ja mal mit den Jungs von FROSH ob es Überschneidungen gibt? 

Shop/Zugang:
https://www.home-coral.de/admin#
BN // PW
[REMOVED]

Besteht die Chance das zu lösen?

Viele Grüße Marco Thrum

**Comment by tinect** [comment]
Hallo,

vorweg:
ich würde dringlichst (!!!!) empfehlen, den geposteten account zu sperren und ein Backup vor Ihrer Nachricht einzuspielen.

Sie schreiben komplett öffentlich.

**Comment by tinect** [comment]
Hallo @xp24,

aufgrund der vorgehenden Nachricht sehen wir uns gezwungen, den Fall zu schließen.

Bitte prüfen Sie Ihren Shop und informieren mindestens Ihre Kunden. Danach können Sie mir gerne eine Testumgebung zur Verfügung stellen und dazu sich mit mir im Slack in Verbindung setzen.

**Comment by xp24** [comment]
Hallo, ... ich war tatsächlich der Meinung das dies hier ein geschlossenes Ticketsystem ist. Scheinbar nein. Accounts natürlich gelöscht, Kunde ist informiert. Das Problem wurde auch scheinbar durch ein anderes Plugin von FROSH (Hilfe bei Entwicklung) zusammen mit dem Minify ausgelöst. Zur Info
