### ISSUE TITLE
gallery-slider don´t work

### ISSUE THREAD

**Issue by tfol2020** [FriendsOfShopware/FroshPlatformHtmlMinify#20]
### PHP Version

8.2

### Shopware Version

6.5.8.2

### Plugin Version

2.0.3

### Actual behaviour

If i activate the plugin my gallery-slider don´t work.
www.lobigo.de

here without activated plugin:
<button class="base-slider-controls-next gallery-slider-controls-next is-nav-next-inside" aria-label="Nächstes" aria-controls="tns4" tabindex="-1" data-controls="next">
        <span class="icon icon-arrow-head-right">
                        <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="24" height="24" viewBox="0 0 24 24"><defs><path id="icons-default-arrow-head-right" d="m11.5 7.9142 10.2929 10.293c.3905.3904 1.0237.3904 1.4142 0 .3905-.3906.3905-1.0238 0-1.4143l-11-11c-.3905-.3905-1.0237-.3905-1.4142 0l-11 11c-.3905.3905-.3905 1.0237 0 1.4142.3905.3905 1.0237.3905 1.4142 0L11.5 7.9142z"></path></defs><use transform="rotate(90 11.5 12)" xlink:href="#icons-default-arrow-head-right" fill="#758CA3" fill-rule="evenodd"></use></svg>
        </span>
 </button>

### Expected behaviour

That the slider also work with activated plugin

### Steps to Reproduce?

activate the plugin

**Comment by tinect** [comment]
Hi @tfol2020,

You might have missed the message?

**Comment by tinect** [comment]
We'll close here due to inactivity.
