### ISSUE TITLE
Error during installation of the plugin

### ISSUE THREAD

**Issue by mw-cgn** [FriendsOfShopware/FroshPlatformHtmlMinify#22]
### PHP Version

8.2.13

### Shopware Version

6.5.8.7

### Plugin Version

2.0.3

### Actual behaviour

Hi dear Frosh-Team, i'm unable to install or uninstall the HTML Minify plugin. Allways get the error: 
Uncaught PHP Exception Shopware\Core\Framework\Plugin\Exception\PluginBaseClassNotFoundException: "The class "Frosh\HtmlMinify\FroshPlatformHtmlMinify" is not found. Probably an class loader error. Check your plugin composer.json" at PluginLifecycleService.php line 486 {"exception":"[object] (Shopware\\Core\\Framework\\Plugin\\Exception\\PluginBaseClassNotFoundException(code: 0): The class \"Frosh\\HtmlMinify\\FroshPlatformHtmlMinify\" is not found. Probably an class loader error. Check your plugin composer.json at /html/shopware/vendor/shopware/core/Framework/Plugin/PluginLifecycleService.php:486)"} []

### Expected behaviour

Successful install or uninstall of the plugin

### Steps to Reproduce?

Loaded the plugin inside the store of my shopware staging installation and tried to install and activate it.

**Comment by tinect** [comment]
Please check the opcache settings. This issues is most likely coming from this managed by your server/hoster.

**Comment by mw-cgn** [comment]
In staging is no OPcache active, but in the main domain there is opcache active. The given size is 64 MB and it is used completely. Cache dynamic is inactive.
I will get to my hoster and ask him, if the opcache of the main domain affects in any way the staging.

**Comment by tinect** [comment]
Any news @mw-cgn ? :-)

**Comment by tinect** [comment]
We'll close here due to inactivity.
