### ISSUE TITLE
Problem beim Installieren

### ISSUE THREAD

**Issue by andrebeyer1979** [FriendsOfShopware/FroshPlatformHtmlMinify#23]
### Question

Hallo ich habe einen Shopware 6.6.5.1 Shop mit PHP 8.3 bei Timmehosting und möchte euer Minify Plugin installieren, aber erhalte immer diese Fehlermeldung. Auch ein Hinweis im Forum, dass nur mit PHP 8.2 funktioniert hat keine Besserung gebracht, wisst ihr was das sein könnte? DANKE DANKE DANKE

Bad Request

Could not execute "composer require" for plugin "FroshPlatformHtmlMinify (frosh/platform-html-minify:2.0.3). Output: In Factory.php line 320: "./composer.json" does not match the expected JSON schema: - require.composer/composer : NULL value found, but a string is required require [--dev] [--dry-run] [--prefer-source] [--prefer-dist] [--prefer-install PREFER-INSTALL] [--fixed] [--no-suggest] [--no-progress] [--no-update] [--no-install] [--no-audit] [--audit-format AUDIT-FORMAT] [--update-no-dev] [-w|--update-with-dependencies] [-W|--update-with-all-dependencies] [--with-dependencies] [--with-all-dependencies] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [-m|--minimal-changes] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--apcu-autoloader-prefix APCU-AUTOLOADER-PREFIX] [--] [...]

**Comment by tinect** [comment]
Hallo @andrebeyer1979,

das sieht komisch aus. Prüfst du mal bitte die composer.json im Root deines Projektes? Die scheint ungültig zu sein.

**Comment by andrebeyer1979** [comment]
Hallo,

mmhhh keine Ahnung, die sieht eigentlich normal aus - denke ich. Hier der Inhalt, habe auch noch ein weiteres Projekt und da lässt sich das Plugin mit dem gleichen Fehler nicht installieren:

{
    "name": "shopware/production",
    "license": "MIT",
    "type": "project",
    "require": {
        "composer-runtime-api": "^2.0",
        "moorl/foundation": "1.6.25",
        "shopware/administration": "6.6.5.1",
        "shopware/conflicts": ">=0.2.0",
        "shopware/core": "6.6.5.1",
        "shopware/elasticsearch": "6.6.5.1",
        "shopware/storefront": "6.6.5.1",
        "symfony/flex": "~2",
        "symfony/runtime": ">=5"
    },
    "repositories": [
        {
            "type": "path",
            "url": "custom/plugins/*",
            "options": {
                "symlink": true
            }
        },
        {
            "type": "path",
            "url": "custom/plugins/*/packages/*",
            "options": {
                "symlink": true
            }
        },
        {
            "type": "path",
            "url": "custom/static-plugins/*",
            "options": {
                "symlink": true
            }
        }
    ],
    "prefer-stable": true,
    "config": {
        "allow-plugins": {
            "symfony/flex": true,
            "symfony/runtime": true
        },
        "optimize-autoloader": true,
        "sort-packages": true
    },
    "scripts": {
        "auto-scripts": {
            "assets:install": "symfony-cmd"
        },
        "post-install-cmd": [
            ***@***.***"
        ],
        "post-update-cmd": [
            ***@***.***"
        ]
    },
    "extra": {
        "symfony": {
            "allow-contrib": true,
            "endpoint": [
                "https://raw.githubusercontent.com/shopware/recipes/flex/main/index.json",
                "flex://defaults"
            ]
        }
    }
}

**Comment by tinect** [comment]
Könntest du mal bitte prüfen, ob es ohne dem Plugin `moorl/foundation` funktioniert?
https://forum.shopware.com/t/update-auf-6-6-4-0-mit-fehler/104470/12

**Comment by andrebeyer1979** [comment]
Meinst du die Zeile in der JSON entfernen oder das Plugin deinstallieren?Am 03.09.2024 um 13:27 schrieb tinect ***@***.***>:﻿
Könntest du mal bitte prüfen, ob es ohne dem Plugin moorl/foundation funktioniert?
https://forum.shopware.com/t/update-auf-6-6-4-0-mit-fehler/104470/12

**Comment by tinect** [comment]
versuch mal zuerst die zeile zu löschen. ich meinte aber komplett deinstallieren.

**Comment by tinect** [comment]
@andrebeyer1979 hast du Feedback?
