### ISSUE TITLE
$content is null after extractCombinedInlineScripts() Method

### ISSUE THREAD

**Issue by Gugiman** [FriendsOfShopware/FroshPlatformHtmlMinify#25]
### PHP Version

8.3

### Shopware Version

6.5.8.13

### Plugin Version

2.0.1

### Actual behaviour

We are using FactFinder Search Engine

This error appers when go to some factfinder search result page:

php.CRITICAL: Uncaught Error: Frosh\HtmlMinify\Service\MinifyService::minifyHtml(): Argument #1 ($content) must be of type string, null given, called in /vendor/frosh/platform-html-minify/src/Service/MinifyService.php on line 40 {"exception":"[object] (TypeError(code: 0): Frosh\\HtmlMinify\\Service\\MinifyService::minifyHtml(): Argument #1 ($content) must be of type string, null given, called in /vendor/frosh/platform-html-minify/src/Service/MinifyService.php on line 40 at /vendor/frosh/platform-html-minify/src/Service/MinifyService.php:57)"} []

### Expected behaviour

Minify is working or checks beforehand that $content is not null

### Steps to Reproduce?

Can't completly tell.

We are using Factfinder search engine.
When typing something in the search bar and press enter, a custom Controller is called:
https://github.com/FACT-Finder-Web-Components/shopware6-plugin/blob/release/4.x/src/Storefront/Controller/ResultController.php#L41

We got that error on spanish but not e.g. in German

Here is the html which resultet in NULL
[contentlog.txt](https://github.com/user-attachments/files/17162397/contentlog.txt)

It seems like the preg_replace_callback in extractCombinedInlineScripts() results in $content == NULL

**Comment by tinect** [comment]
Hi @Gugiman,

I'm a bit confused about the inlined JavaScript in your example. This is really too much produced by FactFinder. This will potentially cause issues with memory and PCRE limits.

While you have an idea, you are welcome to create a PR to resolve this issue.

**Comment by Gugiman** [comment]
Good Morning

I checked for PCRE Limits and that was exactly the problem. I requested an increase of the pcre.backtrack_limit and i think that will solve the problem for me.

I don't think a code change is necessary because this seems to be an edge case. 

Thanks for pointing me to this direction!
