### ISSUE TITLE
Problem mit ShopVote Einbindung Java Skript

### ISSUE THREAD

**Issue by solarvoltgmbh** [FriendsOfShopware/FroshPlatformHtmlMinify#27]
Sehr geehrte Damen und Herren,

Der Test hat gezeigt, dass scheinbar ein Optimierungs- oder Cookie Consent Tool den JavaScript-Code verändert und die Ausführung daher fehlschlägt. Bitte erstellen Sie in dem Tool eine Ausnahme für die Script von SHOPVOTE, da die Funktionsweise sonst nicht sichergestellt werden kann.

Sobald ich von Ihnen "Kombiniere und verkleinere Inline-JavaScript" ausgeschalten habe - wurde ShopVote wieder aktiv.

Können Sie bitte das Problem untersuchen und fixen?

Mit freundlichen Grüßen
Alexander Lösecke

**Comment by tinect** [comment]
Hallo @solarvoltgmbh,

leider ist mir das genannte Plugin nicht bekannt, und ich habe aktuell leider keine Kapazitäten für individuellen Support.

Dieses Plugin ist grundsätzlich nicht darauf ausgelegt, spezifische Ausnahmen für Drittanbieter-Plugins zu integrieren.

Ich empfehle, Ihre Installation individuell überprüfen zu lassen. Oftmals entstehen solche Probleme durch JavaScript-Fehler im Drittanbieter-Plugin, die erst beim Komprimieren auffallen.

Falls es sich jedoch um ein allgemeines Problem handelt, kommen Sie gerne mit genaueren Informationen zur Ursache wieder auf uns zu.

Viele Grüße
Sebastian
