### ISSUE TITLE
Plugin breaks on prod on plugins with bad inline JS

### ISSUE THREAD

**Issue by Gugiman** [FriendsOfShopware/FroshPlatformHtmlMinify#28]
### PHP Version

8.3

### Shopware Version

6.5.8.13

### Plugin Version

2.0.1

### Actual behaviour

Hey guys,

referring to this old issue i can confirm and give more information which can be also a problem on other plugins with bad inline JS.
Therefore the plugin gets more compatible with more plugins (although it maybe encourage them further to use inline js :') )

https://github.com/FriendsOfShopware/FroshPlatformHtmlMinify/issues/11

The problem is, that the extractCombinedInlineScripts() Method places the inline JS to the first occurance of a <script> tag when no placeholder "##SCRIPTPOSITION##" is set.
Therefore some JS might be executed on elements which are not present at this time.

Maybe it would be better to place it at the last occurance of <script>?

Or at least add the information for the placeholder in the README?

### Expected behaviour

Put minified inline js at the last occurance of a <script> tag.
or maybe (untested) place the collected inline js in a "window.onload()" event?

### Steps to Reproduce?

Create a <script> tag early in the dom. e.g. after the <body> tag.
Create a 2nd <script> tag with inline JS after that which manipulate an element which is created right above that 2nd <script> tag.

e.g.

```
<body>
<script>console.log("first tag")</script>
<div id="testDiv"></div>
<script>document.querySelector("#testDiv").classList.add("testClass")</script>
</body>
```

**Comment by tinect** [comment]
I appreciate the idea. 

But most scripts have to be placed at the very top of the code, like tracking once.
Surrounding these with an event will result in no detectable side effects.

That is why I have no idea how to resolve this problem without pointing to the plugin/feature manufacturer to use events in their code.

So, I agree that we should add a note in README and the new [config](https://github.com/FriendsOfShopware/FroshPlatformHtmlMinify/blob/main/src/Resources/config/config.xml#L7) to make clearer why it might not work.
