### ISSUE TITLE
Plugin destroys JS

### ISSUE THREAD

**Issue by faesslich** [FriendsOfShopware/FroshPlatformHtmlMinify#4]
Using the plugin is causing multiple JS errors. 
Some of the code has been written in the javascript file structure and some has been written directly inside of the `base_body_script` block of the template. 

For whatever reason this isn't caused by one code snippet alone. If I simply remove the causing snippet, just another script from any other plugin crashes. 

As you can see, my shop instance doesn't throw notices, warning or errors at all without the plugin activated, but throws a few errors with it been activated. And like I said, if I remove the causing snippets, I get other errors.

**Normally:**
![Screenshot 2021-04-21 082209](https://user-images.githubusercontent.com/48015957/115506317-04caaa80-a27b-11eb-825d-d4c39fb5a6ef.png)

**With plugin:**
![Screenshot 2021-04-21 082251](https://user-images.githubusercontent.com/48015957/115506313-04321400-a27b-11eb-8faa-a7808c74d514.png)

**Comment by tinect** [comment]
Could you please send me the original html-source of the related site to reproduce the error?
Gladly by PM in slack: https://slack.shopware.com/

**Comment by tinect** [comment]
Hey @faesslich 
I'd like to inspect your problem. Therefore, I need some feedback :-)

**Comment by tinect** [comment]
Sadly, it looks like there is no need...
